#!/bin/sh /etc/rc.common

#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=05
STOP=94

USE_PROCD=1

start_service() {
	echo "start qrng service"
	procd_open_instance
	procd_set_param command /sbin/insmod /lib/modules/msm-rng.ko
	procd_close_instance
}

stop_service() {
	echo "Stopping qrng service"
	service_stop /lib/modules/msm-rng.ko
	# commands to kill application
}

