#!/bin/sh /etc/rc.common

#Copyright (c) 2022, 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=06
STOP=93

USE_PROCD=1
PROCD_DEBUG=1

start_service() {
        procd_open_instance
        procd_set_param command insmod /lib/modules/smcinvoke.ko
        procd_close_instance
}

stop_service() {
        procd_set_param rmmod smcinvoke_dlkm
}
