BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS          += "qti-security"
BBFILE_PRIORITY_qti-security = "17"
BBFILE_PATTERN_qti-security := "^${LAYERDIR}/"

BBFILES += "${LAYERDIR}/recipes/*/*.bb \
            ${LAYERDIR}/recipes/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
